# -*- coding: utf-8 -*-
"""doc_retrieval.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10f48l88jq-davbg6xbRgl6HTiCt2wvaZ
"""

!pip install langchain

!pip install chromadb

!pip install openai

!pip install tiktoken

import os


from langchain.llms import OpenAI
from langchain.document_loaders import WebBaseLoader
os.environ["OPENAI_API_KEY"] ='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'

loader = WebBaseLoader("https://www.roughguides.com/articles/yoga-meditation-ashrams/")
data = loader.load()
from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size = 500, chunk_overlap = 0)
all_splits = text_splitter.split_documents(data)
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Chroma

vectorstore = Chroma.from_documents(documents=all_splits, embedding=OpenAIEmbeddings())
question = "Describe the Ashtanga yoga?"
docs = vectorstore.similarity_search(question)
len(docs)
from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI

llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)
qa_chain = RetrievalQA.from_chain_type(llm,retriever=vectorstore.as_retriever())
qa_chain({"query": question})